services:
  - type: web
    name: telegram-business-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python render_bot.py
    plan: free
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
        # חובה! יש להוסיף את הטוקן של הבוט מ-BotFather בפאנל רנדר
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true
