services:
  - type: web
    name: telegram-business-bot
    env: python
    buildCommand: pip install -r requirements.txt && chmod +x start.sh
    startCommand: ./start.sh
    plan: free
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src
